### ISSUE TITLE
apply not obeying spec

### ISSUE THREAD

**Issue by kstrasser** [mgorlick/CRESTaceans#10]
> (motile/start (motile/compile '(apply + '(1 2 3))) BASELINE)
> . . baseline.rkt:118:13: +: expects argument of type <number>; given '(1 2 3)

**Comment by mgorlick** [comment]
kstrasser wrote:

> > (motile/start (motile/compile '(apply + '(1 2 3))) BASELINE)
> > 
> > . . baseline.rkt:118:13: +: expects argument of type<number>; given '(1 2 3)
> 
> Apropos of your discovery that (when ...) fails I just noticed that I 
> neglected to update (unless ...) as well when modifying the compiler for 
> managing global binding environments.
