### ISSUE TITLE
Tuple functions reorder the tuple

### ISSUE THREAD

**Issue by kstrasser** [mgorlick/CRESTaceans#12]
> (tuple 1 3 4 6 2 2)
'#(<tuple> 1 3 4 6 2 2)
> (tuple/drop/left (tuple 1 3 4 6 2 2) 3)
'#(3 4 <tuple> 2 2)

Seems like everything that calls tuple/copy is affected.

**Comment by mgorlick** [comment]
Yes, indeed. tuple/copy is the culprit and it has been fixed in a version of persistent/tuple.rkt that will be pushed to repository along with the new Motile compiler.
